name: 'fakeflix'

services:
  db:
    image: bitnami/postgresql:latest
    container_name: fakeflix-db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - .data:/var/lib/postgresql/data
    profiles:
      - dev
      - prod

  test_db:
    image: bitnami/postgresql:latest
    container_name: fakeflix-test-db
    ports:
      - 5433:5433
    env_file:
      - .env.test
    volumes:
      - .data:/var/lib/postgresql/data
    profiles:
      - test
