name: 'fakeflix'

services:
  db:
    image: postgres:15-alpine
    container_name: fakeflix-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fakeflix_dev
    ports:
      - '5432:5432'
    volumes:
      - .data:/var/lib/postgresql/data

  db-test:
    image: postgres:15-alpine
    container_name: fakeflix-test-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fakeflix_test
    ports:
      - '5433:5432'
    volumes:
      - .data:/var/lib/postgresql/test/data
